# Activer Spring Cloud Config
spring.cloud.config.enabled=true

# Configuration du client Eureka
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/

# l'acc�s � endpoints actuator
management.endpoints.web.exposure.include=*

# Configuration de Hibernate
spring.jpa.hibernate.ddl-auto=update

# Configuration de la base de donn�e postgresql
spring.datasource.url=jdbc:postgresql://projetdb-central:5432/expensedb
spring.datasource.username=dev
spring.datasource.password=Salma123@
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration de l'API Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Configuration de keyclock
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloakk:8080/realms/pfe-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloakk:8080/realms/pfe-realm/protocol/openid-connect/certs

# Configuration de spring batch
spring.batch.jdbc.initialize-schema=always
