# Adresse du broker Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notes-frais-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


# Activer Spring Cloud Config
spring.cloud.config.enabled=true

# Configuration du client Eureka
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# l'accès à endpoints actuator
management.endpoints.web.exposure.include=*

# Configuration de Hibernate
spring.jpa.hibernate.ddl-auto=update

# Configuration de la base de donnée postgresql
spring.datasource.url=jdbc:postgresql://localhost:5455/projetdb
spring.datasource.username=dev
spring.datasource.password=Salma123@
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration de l'API Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Configuration de keyclock
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/pfe-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/pfe-realm/protocol/openid-connect/certs

# Configuration de spring batch
spring.batch.jdbc.initialize-schema=always


spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=harbisalma524@gmail.com
spring.mail.password=redi scfl yzer arkd 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true