spring.application.name=ConfigService
server.port=9999

# Lien vers le dépôt Git
spring.cloud.config.server.git.uri=https://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@github.com/SalmaHarbi/ConfigServer-PFE.git

# Clone automatiquement le dépôt Git au démarrage de l'application.
spring.cloud.config.server.git.clone-on-start=true

# Expose tous les endpoints de management (actuator) via le web
management.endpoints.web.exposure.include=*

# Configuration d'Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.discovery.enabled=true
eureka.instance.prefer-ip-address=true
