spring.application.name=ConfigService

server.port=9999
spring.cloud.discovery.enabled=true

spring.cloud.config.server.git.uri=https://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@github.com/SalmaHarbi/ProjetPFE.git

spring.cloud.config.server.git.clone-on-start=true


management.endpoints.web.exposure.include=*


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
